# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "9.4.0"
    working_directory: /Users/distiller/project
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    steps:
      - checkout

      # Build the app and run tests
      - run:
          name: pre-start simulator
          command: xcrun instruments -w "iPhone 7 (11.4) [" || true
      - run:
          name: Build and run tests
          command: set -o pipefail && xcodebuild -workspace iOSBoilerplate.xcworkspace -scheme 'iOSBoilerplate' clean build test -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.4' CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= PROVISIONING_PROFILE= | tee '/Users/distiller/Library/Logs/scan/iOSBoilerplate-iOSBoilerplate.log' | xcpretty --color --report junit --output report.xml
          environment:
            SCAN_DEVICE: iPhone 7
            SCAN_SCHEME: iOSBoilerplate

      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_test_results:
          path: /
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs